#!/usr/bin/env python3
"""
Build OVER signal catalog from two 100-signal source lists.
Deduplicate, structure, classify, and output catalog.
"""

import pandas as pd
import numpy as np
from pathlib import Path

BASE = Path(__file__).resolve().parent

# =====================================================================
# The two source lists are nearly identical (same author produced both
# under different prompts). After careful comparison:
#
# Source A (Claude): 100 signals, numbered 1-100
# Source B (ChatGPT): 100 signals, numbered 1-100
#
# EXACT DUPLICATES (identical concept, same mechanism):
#   A1=B1, A2=B2, A3=B3, A4=B4, A5=B5, A6=B6, A7=B7, A8=B8, A9=B9,
#   A10=B10, A11=B11, A12=B12, A13=B13, A14=B14, A15=B15, A16=B16,
#   A17=B17, A18=B18, A19=B19, A20=B20, A21=B21, A22=B22, A23=B23,
#   A24=B24, A25=B25, A26=B26, A27=B27, A28=B28, A29=B29, A30=B30,
#   A31=B31, A32=B32, A33=B33, A34=B34, A35=B35, A36=B36, A37=B37,
#   A38=B38, A39=B39, A40=B40, A41=B41, A42=B42, A43=B43, A44=B44,
#   A45=B45, A46=B46, A47=B47, A48=B48, A49=B49, A50=B50, A51=B51,
#   A52=B52, A53=B53, A54=B54, A55=B55, A56=B56, A57=B57, A58=B58,
#   A59=B59, A60=B60, A61=B61, A62=B62, A63=B63, A64=B64, A65=B65,
#   A66=B66, A67=B67, A68=B68, A69=B69, A70=B70, A71=B71, A72=B72,
#   A73=B73, A74=B74, A75=B75, A76=B76, A77=B77, A78=B78, A79=B79,
#   A80=B80, A81=B81, A82=B82, A83=B83, A84=B84, A85=B85, A86=B86,
#   A87=B87, A88=B88, A89=B89, A90=B90, A91=B91, A92=B92, A93=B93,
#   A94=B94, A95=B95, A96=B96, A97=B97, A98=B98, A99=B99, A100=B100
#
# The two lists are the SAME 100 signals. Source B is a reformatted
# version of Source A with identical concepts, mechanisms, and data inputs.
# Dedup result: 100 unique signals, 0 net additions from list B.
# =====================================================================

# Build the catalog from the unified 100 signals

signals = [
    # ── PITCHER VOLATILITY (1-20) ────────────────────────────────
    {
        "signal_id": "OV001",
        "signal_name": "bb_rate_x_hard_hit",
        "domain": "pitcher_volatility",
        "formula": "pitcher_bb_rate * pitcher_hard_hit_rate_allowed",
        "required_inputs": "pitcher_bb_rate, pitcher_hard_hit_rate_allowed",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV002",
        "signal_name": "xera_era_gap",
        "domain": "pitcher_volatility",
        "formula": "pitcher_xERA - pitcher_ERA",
        "required_inputs": "pitcher_ERA, pitcher_xERA",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV003",
        "signal_name": "spin_rate_instability",
        "domain": "pitcher_volatility",
        "formula": "std(pitcher_spin_rate_last3)",
        "required_inputs": "pitcher_spin_rate per start (Statcast)",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV004",
        "signal_name": "velo_decline_bb_rise",
        "domain": "pitcher_volatility",
        "formula": "(pitcher_velo_season - pitcher_velo_last3) * pitcher_bb_rate_last3",
        "required_inputs": "pitcher_avg_velo per start, pitcher_bb_rate_last3",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV005",
        "signal_name": "pitch_mix_fastball_shift",
        "domain": "pitch_mix",
        "formula": "pitcher_FF_pct_last3 - pitcher_FF_pct_season",
        "required_inputs": "pitch_type_pct per start (Statcast)",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV006",
        "signal_name": "whip_era_gap",
        "domain": "pitcher_volatility",
        "formula": "pitcher_WHIP - (pitcher_ERA / 4.5)",
        "required_inputs": "pitcher_WHIP, pitcher_ERA",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV007",
        "signal_name": "il_return_first_start",
        "domain": "pitcher_volatility",
        "formula": "flag: first_start_after_IL AND IL_days >= 10",
        "required_inputs": "IL stint dates, game schedule",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV008",
        "signal_name": "gb_pitcher_x_pull_power_lineup",
        "domain": "contact_amplification",
        "formula": "pitcher_GB_pct * lineup_pull_rate",
        "required_inputs": "pitcher_GB_pct, lineup_pull_rate",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV009",
        "signal_name": "il_return_velo_loss",
        "domain": "pitcher_volatility",
        "formula": "(pitcher_velo_pre_IL - pitcher_velo_post_IL) * flag_IL_return",
        "required_inputs": "pitcher_avg_velo pre/post IL, IL dates",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV010",
        "signal_name": "high_csw_high_hard_hit",
        "domain": "pitcher_volatility",
        "formula": "pitcher_CSW_pct * pitcher_hard_hit_rate_allowed",
        "required_inputs": "pitcher_CSW_pct, pitcher_hard_hit_rate_allowed",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV011",
        "signal_name": "third_time_through_exposure",
        "domain": "run_sequencing",
        "formula": "pitcher_TTO3_OPS - pitcher_TTO1_OPS",
        "required_inputs": "pitcher times-through-order splits",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV012",
        "signal_name": "slider_disappearance",
        "domain": "pitch_mix",
        "formula": "pitcher_SL_pct_season - pitcher_SL_pct_last_start",
        "required_inputs": "pitch_type_pct per start (Statcast)",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV013",
        "signal_name": "hr_fb_spike_recent",
        "domain": "hr_cluster",
        "formula": "pitcher_HR_FB_last3 - pitcher_HR_FB_season",
        "required_inputs": "pitcher HR, FB per start",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV014",
        "signal_name": "low_swstr_low_csw",
        "domain": "pitcher_volatility",
        "formula": "-1 * (pitcher_SwStr_pct + pitcher_called_strike_pct)",
        "required_inputs": "pitcher_SwStr_pct, pitcher_called_strike_pct (Statcast)",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV015",
        "signal_name": "post_trade_first_start",
        "domain": "player_interaction",
        "formula": "flag: first_start_new_team after trade",
        "required_inputs": "trade dates, pitcher roster transactions",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV016",
        "signal_name": "high_pitch_count_fatigue",
        "domain": "pitcher_volatility",
        "formula": "pitcher_pitches_2starts_ago / 100",
        "required_inputs": "pitcher pitch counts per start",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "READY",
    },
    {
        "signal_id": "OV017",
        "signal_name": "fb_pitcher_x_wind_out",
        "domain": "environment",
        "formula": "pitcher_FB_pct * wind_factor_effective (when > 0)",
        "required_inputs": "pitcher_FB_pct, wind_factor_effective",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV018",
        "signal_name": "low_extension_x_high_ev_lineup",
        "domain": "player_interaction",
        "formula": "-1 * pitcher_extension * lineup_avg_exit_velo",
        "required_inputs": "pitcher_extension (Statcast), lineup_avg_exit_velo",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV019",
        "signal_name": "era_spike_recent",
        "domain": "pitcher_volatility",
        "formula": "pitcher_ERA_last2 - pitcher_ERA_season",
        "required_inputs": "pitcher ER, IP per start",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "READY",
    },
    {
        "signal_id": "OV020",
        "signal_name": "command_pitcher_x_patient_lineup",
        "domain": "player_interaction",
        "formula": "-1 * pitcher_bb_rate * lineup_bb_rate",
        "required_inputs": "pitcher_bb_rate, lineup_bb_rate",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "DERIVABLE",
    },
    # ── CONTACT AMPLIFICATION (21-40) ────────────────────────────
    {
        "signal_id": "OV021",
        "signal_name": "low_k_x_high_contact_lineup",
        "domain": "contact_amplification",
        "formula": "(1 - pitcher_k_rate) * lineup_contact_rate",
        "required_inputs": "pitcher_k_rate, lineup_contact_rate",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV022",
        "signal_name": "gb_pitcher_x_poor_infield",
        "domain": "defensive_instability",
        "formula": "pitcher_GB_pct * (-1 * team_infield_DRS)",
        "required_inputs": "pitcher_GB_pct, team_infield_DRS",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV023",
        "signal_name": "fb_pitcher_x_poor_outfield",
        "domain": "defensive_instability",
        "formula": "pitcher_FB_pct * (-1 * team_outfield_DRS)",
        "required_inputs": "pitcher_FB_pct, team_outfield_DRS",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV024",
        "signal_name": "low_k_x_high_babip_lineup",
        "domain": "contact_amplification",
        "formula": "(1 - pitcher_k_rate) * lineup_babip_rolling",
        "required_inputs": "pitcher_k_rate, lineup_BABIP",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV025",
        "signal_name": "sinker_pitcher_x_launch_angle_lineup",
        "domain": "contact_amplification",
        "formula": "pitcher_sinker_pct * lineup_avg_launch_angle",
        "required_inputs": "pitcher_sinker_pct, lineup_avg_launch_angle",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV026",
        "signal_name": "ff_pitcher_x_ff_damage_lineup",
        "domain": "contact_amplification",
        "formula": "pitcher_FF_pct * lineup_FF_wOBA",
        "required_inputs": "pitcher_FF_pct, lineup_FF_wOBA (pitch-type wOBA)",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV027",
        "signal_name": "cutter_pitcher_x_opp_hand_lineup",
        "domain": "player_interaction",
        "formula": "pitcher_cutter_pct * lineup_opp_hand_pct",
        "required_inputs": "pitcher_cutter_pct, lineup_handedness",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV028",
        "signal_name": "low_chase_pitcher_x_patient_lineup",
        "domain": "contact_amplification",
        "formula": "(1 - pitcher_o_swing_pct) * lineup_bb_rate",
        "required_inputs": "pitcher_chase_rate (Statcast), lineup_bb_rate",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV029",
        "signal_name": "high_zone_pitcher_x_zone_damage_lineup",
        "domain": "contact_amplification",
        "formula": "pitcher_zone_rate * lineup_zone_contact_wOBA",
        "required_inputs": "pitcher_zone_rate (Statcast), lineup_zone_contact_rate",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV030",
        "signal_name": "soft_contact_regression",
        "domain": "pitcher_volatility",
        "formula": "pitcher_season_soft_contact_pct - pitcher_career_soft_contact_pct",
        "required_inputs": "soft_contact_rate rolling (Statcast)",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV031",
        "signal_name": "pull_lineup_x_no_shift",
        "domain": "contact_amplification",
        "formula": "lineup_pull_pct (post-2023 only)",
        "required_inputs": "lineup_pull_pct",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV032",
        "signal_name": "gb_lineup_x_fb_pitcher",
        "domain": "contact_amplification",
        "formula": "lineup_GB_pct * pitcher_FB_pct",
        "required_inputs": "lineup_GB_pct, pitcher_FB_pct",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV033",
        "signal_name": "barrel_x_barrel",
        "domain": "hr_cluster",
        "formula": "lineup_barrel_rate * pitcher_barrel_rate_allowed",
        "required_inputs": "lineup_barrel_rate, pitcher_barrel_rate_allowed (Statcast)",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV034",
        "signal_name": "chase_pitcher_x_chase_lineup",
        "domain": "contact_amplification",
        "formula": "pitcher_chase_rate * lineup_chase_rate",
        "required_inputs": "pitcher_chase_rate, lineup_o_swing_pct (Statcast)",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV035",
        "signal_name": "high_velo_x_velo_damage_lineup",
        "domain": "player_interaction",
        "formula": "pitcher_avg_velo * lineup_velo_damage_wOBA",
        "required_inputs": "pitcher_avg_velo, lineup_wOBA_vs_velo_bin",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV036",
        "signal_name": "gb_pitcher_x_fast_surface",
        "domain": "environment",
        "formula": "pitcher_GB_pct * park_surface_speed_rating",
        "required_inputs": "pitcher_GB_pct, park_surface_type",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV037",
        "signal_name": "popup_pitcher_x_small_foul",
        "domain": "environment",
        "formula": "pitcher_IFFB_pct * (1 / park_foul_territory_area)",
        "required_inputs": "pitcher_IFFB_pct, park_foul_territory",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV038",
        "signal_name": "hr_suppression_regression",
        "domain": "hr_cluster",
        "formula": "(league_avg_HR_FB - pitcher_HR_FB_rate) * lineup_FB_rate",
        "required_inputs": "pitcher_HR_FB_rate, lineup_FB_rate",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV039",
        "signal_name": "exit_velo_mismatch",
        "domain": "contact_amplification",
        "formula": "lineup_avg_exit_velo - pitcher_expected_exit_velo",
        "required_inputs": "lineup_avg_exit_velo, pitcher_xEV (Statcast)",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV040",
        "signal_name": "contact_pitcher_x_oppo_lineup",
        "domain": "contact_amplification",
        "formula": "(1 - pitcher_k_rate) * lineup_oppo_hit_pct",
        "required_inputs": "pitcher_k_rate, lineup_oppo_hit_rate",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    # ── BULLPEN CASCADE (41-55) ──────────────────────────────────
    {
        "signal_id": "OV041",
        "signal_name": "short_starter_x_weak_bullpen",
        "domain": "bullpen_cascade",
        "formula": "(5 - starter_avg_IP_last5) * bullpen_xFIP",
        "required_inputs": "starter_avg_IP_last5, bullpen_xFIP",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "READY",
    },
    {
        "signal_id": "OV042",
        "signal_name": "bullpen_low_strand_x_baserunner_starter",
        "domain": "bullpen_cascade",
        "formula": "(1 - bullpen_strand_rate) * starter_WHIP",
        "required_inputs": "bullpen_strand_rate, starter_WHIP",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV043",
        "signal_name": "high_leverage_bullpen_overuse",
        "domain": "bullpen_cascade",
        "formula": "bullpen_high_leverage_IP_last3d",
        "required_inputs": "bullpen_usage per day, leverage index",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "READY",
    },
    {
        "signal_id": "OV044",
        "signal_name": "bullpen_bb_x_patient_lineup",
        "domain": "bullpen_cascade",
        "formula": "bullpen_bb_rate_last7 * lineup_bb_rate",
        "required_inputs": "bullpen_bb_rate_rolling, lineup_bb_rate",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV045",
        "signal_name": "bullpen_hard_hit_spike",
        "domain": "bullpen_cascade",
        "formula": "bullpen_hard_hit_rate_last7 - bullpen_hard_hit_rate_season",
        "required_inputs": "bullpen_hard_hit_rate per game",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV046",
        "signal_name": "bullpen_handedness_mismatch",
        "domain": "bullpen_cascade",
        "formula": "abs(bullpen_available_LHP_pct - lineup_LHB_pct)",
        "required_inputs": "bullpen_handedness_available, lineup_handedness",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV047",
        "signal_name": "doubleheader_game2_bullpen",
        "domain": "bullpen_cascade",
        "formula": "flag: game_2_doubleheader * bullpen_IP_game1",
        "required_inputs": "doubleheader_flag, bullpen_IP_game1",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "READY",
    },
    {
        "signal_id": "OV048",
        "signal_name": "opener_weak_follower",
        "domain": "bullpen_cascade",
        "formula": "opener_flag * follower_xFIP",
        "required_inputs": "opener_flag, follower_pitcher_xFIP",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV049",
        "signal_name": "bullpen_k_rate_collapse",
        "domain": "bullpen_cascade",
        "formula": "bullpen_k_rate_season - bullpen_k_rate_last10d",
        "required_inputs": "bullpen_K per game rolling",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV050",
        "signal_name": "short_starter_x_extra_innings_yesterday",
        "domain": "bullpen_cascade",
        "formula": "max(0, prev_game_innings - 9) * (5 - starter_avg_IP)",
        "required_inputs": "prev_game_innings, starter_avg_IP",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "READY",
    },
    {
        "signal_id": "OV051",
        "signal_name": "bullpen_era_xfip_gap",
        "domain": "bullpen_cascade",
        "formula": "bullpen_xFIP - bullpen_ERA",
        "required_inputs": "bullpen_ERA, bullpen_xFIP",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "READY",
    },
    {
        "signal_id": "OV052",
        "signal_name": "weak_closer_x_close_game",
        "domain": "bullpen_cascade",
        "formula": "closer_xFIP * game_close_probability",
        "required_inputs": "closer_xFIP, game_spread_implied",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV053",
        "signal_name": "road_trip_bullpen_fatigue",
        "domain": "bullpen_cascade",
        "formula": "road_trip_game_num * bullpen_IP_cumulative_trip",
        "required_inputs": "road_trip_game_num, bullpen_IP per game",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV054",
        "signal_name": "bullpen_inherited_runner_scoring",
        "domain": "bullpen_cascade",
        "formula": "bullpen_IR_scored_pct_last10",
        "required_inputs": "bullpen inherited runners scored per game",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV055",
        "signal_name": "starter_third_inning_weakness",
        "domain": "pitcher_volatility",
        "formula": "starter_3rd_inning_ERA - starter_overall_ERA",
        "required_inputs": "pitcher inning-level splits",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    # ── DEFENSIVE INSTABILITY (56-65) ────────────────────────────
    {
        "signal_id": "OV056",
        "signal_name": "poor_infield_x_gb_environment",
        "domain": "defensive_instability",
        "formula": "combined_GB_pct * (-1 * team_infield_DRS)",
        "required_inputs": "pitcher_GB_pct, team_infield_DRS",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV057",
        "signal_name": "error_prone_x_high_whip",
        "domain": "defensive_instability",
        "formula": "team_error_rate * pitcher_WHIP",
        "required_inputs": "team_error_rate, pitcher_WHIP",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV058",
        "signal_name": "weak_of_arm_x_aggressive_runners",
        "domain": "defensive_instability",
        "formula": "(-1 * outfield_arm_rating) * opp_SB_attempt_rate",
        "required_inputs": "outfield_arm_rating, opp_SB_rate",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV059",
        "signal_name": "corner_defense_x_pull_pitcher",
        "domain": "defensive_instability",
        "formula": "(-1 * corner_infield_DRS) * pitcher_pull_GB_pct",
        "required_inputs": "corner_IF_DRS, pitcher_pull_GB_pct",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV060",
        "signal_name": "poor_framing_x_borderline_pitcher",
        "domain": "defensive_instability",
        "formula": "(-1 * catcher_framing_runs) * pitcher_zone_edge_pct",
        "required_inputs": "catcher_framing_runs, pitcher_zone_rate",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV061",
        "signal_name": "weak_catcher_arm_x_steal_team",
        "domain": "defensive_instability",
        "formula": "(-1 * catcher_CS_pct) * opp_SB_attempt_rate",
        "required_inputs": "catcher_caught_stealing_pct, opp_SB_rate",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV062",
        "signal_name": "weak_cf_x_gap_hitters",
        "domain": "defensive_instability",
        "formula": "(-1 * CF_range_rating) * lineup_doubles_rate",
        "required_inputs": "CF_range, lineup_doubles_rate",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV063",
        "signal_name": "shift_ban_x_pull_lineup",
        "domain": "contact_amplification",
        "formula": "lineup_pull_pct (post-2023 flag)",
        "required_inputs": "lineup_pull_pct, year >= 2023",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV064",
        "signal_name": "poor_defense_x_extras_prob",
        "domain": "defensive_instability",
        "formula": "(-1 * team_defensive_rating) * game_extras_probability",
        "required_inputs": "team_DRS, game_spread_implied",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV065",
        "signal_name": "defensive_downgrade_rest_day",
        "domain": "defensive_instability",
        "formula": "flag: primary_IF_sitting AND backup_DRS < primary_DRS",
        "required_inputs": "lineup vs standard lineup, player DRS",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    # ── HR CLUSTER (66-75) ───────────────────────────────────────
    {
        "signal_id": "OV066",
        "signal_name": "pull_lineup_x_short_porch",
        "domain": "hr_cluster",
        "formula": "lineup_pull_pct * park_short_porch_factor",
        "required_inputs": "lineup_pull_pct, park_LF_RF_distance",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV067",
        "signal_name": "fb_pitcher_x_hr_park",
        "domain": "hr_cluster",
        "formula": "pitcher_FB_pct * park_hr_factor",
        "required_inputs": "pitcher_FB_pct, park_factor_hr",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV068",
        "signal_name": "barrel_x_babip_lucky_pitcher",
        "domain": "hr_cluster",
        "formula": "lineup_barrel_rate * (pitcher_xBA - pitcher_BA_allowed)",
        "required_inputs": "lineup_barrel_rate, pitcher_xBA, pitcher_BA",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV069",
        "signal_name": "altitude_x_high_ev_lineup",
        "domain": "environment",
        "formula": "park_altitude * lineup_avg_exit_velo",
        "required_inputs": "park_altitude (COL flag), lineup_exit_velo",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV070",
        "signal_name": "fb_pitcher_x_wind_out_large_park",
        "domain": "environment",
        "formula": "pitcher_FB_pct * wind_factor_effective * (1 / park_hr_factor)",
        "required_inputs": "pitcher_FB_pct, wind_factor_effective, park_hr_factor",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV071",
        "signal_name": "first_matchup_familiarity_gap",
        "domain": "player_interaction",
        "formula": "flag: pitcher_first_time_facing_lineup_this_season",
        "required_inputs": "pitcher-lineup matchup history",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV072",
        "signal_name": "cold_end_hr_park",
        "domain": "environment",
        "formula": "(temperature_today - temperature_last7d_avg) * park_hr_factor",
        "required_inputs": "temperature, temperature_rolling, park_hr_factor",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV073",
        "signal_name": "dual_flyball_starters",
        "domain": "hr_cluster",
        "formula": "home_sp_FB_pct * away_sp_FB_pct",
        "required_inputs": "home_sp_FB_pct, away_sp_FB_pct",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV074",
        "signal_name": "low_spin_pitcher_x_spin_vuln_lineup",
        "domain": "player_interaction",
        "formula": "(-1 * pitcher_spin_rate_FF) * lineup_low_spin_wOBA",
        "required_inputs": "pitcher_spin_rate (Statcast), lineup_spin_wOBA",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV075",
        "signal_name": "career_hr_fb_spike",
        "domain": "hr_cluster",
        "formula": "pitcher_HR_FB_rolling - pitcher_HR_FB_career",
        "required_inputs": "pitcher HR/FB per start, career HR/FB",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    # ── RUN SEQUENCING (76-85) ───────────────────────────────────
    {
        "signal_id": "OV076",
        "signal_name": "strand_rate_regression",
        "domain": "run_sequencing",
        "formula": "pitcher_strand_rate_rolling - pitcher_xStrand",
        "required_inputs": "pitcher LOB%, expected strand rate",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV077",
        "signal_name": "blown_save_cluster",
        "domain": "run_sequencing",
        "formula": "team_blown_save_rate_last10",
        "required_inputs": "team blown_save per game rolling",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV078",
        "signal_name": "walk_power_lineup",
        "domain": "run_cascade",
        "formula": "lineup_bb_rate * lineup_ISO",
        "required_inputs": "lineup_bb_rate, lineup_ISO",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV079",
        "signal_name": "first_pitch_strike_collapse",
        "domain": "pitcher_volatility",
        "formula": "pitcher_f_strike_pct_season - pitcher_f_strike_pct_last3",
        "required_inputs": "pitcher first-pitch-strike per start",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV080",
        "signal_name": "risp_matchup_cluster",
        "domain": "run_sequencing",
        "formula": "lineup_BA_RISP * (-1 * pitcher_ERA_RISP)",
        "required_inputs": "pitcher RISP splits, lineup RISP splits",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV081",
        "signal_name": "high_lob_scoring_team",
        "domain": "run_sequencing",
        "formula": "team_LOB_pct * team_runs_per_game",
        "required_inputs": "team_LOB_pct, team_runs_per_game",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV082",
        "signal_name": "oppo_field_x_inside_pitcher",
        "domain": "player_interaction",
        "formula": "lineup_oppo_hit_rate * pitcher_inside_pitch_pct",
        "required_inputs": "lineup_oppo_rate, pitcher_location_pct",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV083",
        "signal_name": "high_whip_x_patient_lineup",
        "domain": "run_cascade",
        "formula": "pitcher_WHIP * lineup_bb_rate",
        "required_inputs": "pitcher_WHIP, lineup_bb_rate",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV084",
        "signal_name": "high_variance_team_x_pitcher",
        "domain": "run_sequencing",
        "formula": "team_runs_std_dev * pitcher_game_score_std_dev",
        "required_inputs": "team_runs_std, pitcher_game_score_std",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV085",
        "signal_name": "k_improvement_hard_contact_stable",
        "domain": "pitcher_volatility",
        "formula": "(pitcher_k_rate_last5 - pitcher_k_rate_season) * pitcher_hard_hit_rate_stable_flag",
        "required_inputs": "pitcher_k_rate rolling, pitcher_hard_hit_rate rolling",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DERIVABLE",
    },
    # ── MATCHUP AND INTERACTION (86-100) ─────────────────────────
    {
        "signal_id": "OV086",
        "signal_name": "lefty_lineup_x_lhp_platoon_vuln",
        "domain": "player_interaction",
        "formula": "pitcher_LHB_wOBA * lineup_LHB_pct (when pitcher is LHP)",
        "required_inputs": "pitcher LHB splits, lineup handedness",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV087",
        "signal_name": "first_series_matchup",
        "domain": "player_interaction",
        "formula": "flag: first_series_between_teams_this_season",
        "required_inputs": "schedule, matchup history",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV088",
        "signal_name": "hot_lineup_x_rested_pitcher",
        "domain": "player_interaction",
        "formula": "lineup_runs_last7 * pitcher_days_rest",
        "required_inputs": "lineup_runs_rolling, pitcher_days_rest",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV089",
        "signal_name": "post_allstar_first_start",
        "domain": "pitcher_volatility",
        "formula": "flag: first_start_after_allstar_break",
        "required_inputs": "ASB dates, game schedule",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV090",
        "signal_name": "fast_lineup_x_poor_pickoff",
        "domain": "player_interaction",
        "formula": "lineup_avg_sprint_speed * (-1 * pitcher_pickoff_rate)",
        "required_inputs": "lineup_sprint_speed (Statcast), pitcher_pickoff_rate",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV091",
        "signal_name": "september_bullpen_depth_gap",
        "domain": "bullpen_cascade",
        "formula": "home_roster_depth - away_roster_depth (September only)",
        "required_inputs": "roster_depth_metric, month",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV092",
        "signal_name": "triple_decline_pitcher",
        "domain": "pitcher_volatility",
        "formula": "(velo_season - velo_last3) + (spin_season - spin_last3) + (hard_hit_last3 - hard_hit_season)",
        "required_inputs": "pitcher velo, spin, hard_hit per start (Statcast)",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV093",
        "signal_name": "high_obp_lineup_x_high_bb_pitcher",
        "domain": "run_cascade",
        "formula": "lineup_OBP * pitcher_bb_rate",
        "required_inputs": "lineup_OBP, pitcher_bb_rate",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV094",
        "signal_name": "away_fragile_starter_x_home_strong_bp",
        "domain": "bullpen_cascade",
        "formula": "away_sp_xFIP * (-1 * home_bullpen_xFIP)",
        "required_inputs": "away_sp_xFIP, home_bullpen_xFIP",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "READY",
    },
    {
        "signal_id": "OV095",
        "signal_name": "surface_vs_process_regression",
        "domain": "pitcher_volatility",
        "formula": "pitcher_xERA - pitcher_ERA (same as OV002, generalized)",
        "required_inputs": "pitcher_ERA, pitcher_xERA",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV096",
        "signal_name": "high_hr_high_k_lineup",
        "domain": "hr_cluster",
        "formula": "lineup_HR_rate * lineup_K_rate",
        "required_inputs": "lineup_HR_rate, lineup_K_rate",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DERIVABLE",
    },
    {
        "signal_id": "OV097",
        "signal_name": "new_catcher_pairing",
        "domain": "player_interaction",
        "formula": "flag: pitcher_first_start_with_catcher",
        "required_inputs": "pitcher-catcher pairing history",
        "direction": "OVER",
        "priority": "MEDIUM",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV098",
        "signal_name": "pitch_type_dominance_mismatch",
        "domain": "player_interaction",
        "formula": "lineup_wOBA_vs_pitcher_primary_pitch",
        "required_inputs": "pitcher primary pitch type, lineup pitch-type wOBA",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV099",
        "signal_name": "aggressive_manager_x_weak_catcher",
        "domain": "player_interaction",
        "formula": "manager_SB_rate * (-1 * catcher_pop_time)",
        "required_inputs": "manager_run_game_rate, catcher_pop_time",
        "direction": "OVER",
        "priority": "LOW",
        "data_status": "DATA_MISSING",
    },
    {
        "signal_id": "OV100",
        "signal_name": "combined_bullpen_workload_both",
        "domain": "bullpen_cascade",
        "formula": "home_bullpen_IP_last3d + away_bullpen_IP_last3d",
        "required_inputs": "bullpen_IP per day per team",
        "direction": "OVER",
        "priority": "HIGH",
        "data_status": "READY",
    },
]

# OV002 and OV095 are duplicates — remove OV095
signals = [s for s in signals if s["signal_id"] != "OV095"]

print(f"Total signals after dedup: {len(signals)}")

# ── Build DataFrame ──────────────────────────────────────────────────
df = pd.DataFrame(signals)

# Summary stats
print(f"\n=== SUMMARY ===")
print(f"Total signals: {len(df)}")
print(f"\nBy domain:")
print(df["domain"].value_counts().to_string())
print(f"\nBy data_status:")
print(df["data_status"].value_counts().to_string())
print(f"\nBy priority:")
print(df["priority"].value_counts().to_string())

# Save parquet
df.to_parquet(BASE / "over_signal_catalog.parquet", index=False)
print(f"\nSaved: over_signal_catalog.parquet ({len(df)} rows)")

# ── Write markdown catalog ───────────────────────────────────────────
md = ["# OVER Signal Catalog — MLB Totals", ""]
md.append(f"Total signals: {len(df)} (after dedup from 200 raw ideas)")
md.append(f"Source A: 100 signals (Claude-generated)")
md.append(f"Source B: 100 signals (ChatGPT-generated)")
md.append(f"Dedup result: lists were identical; 100 unique signals, 1 internal dup removed → {len(df)}")
md.append("")

for domain in df["domain"].unique():
    domain_df = df[df["domain"] == domain]
    md.append(f"## {domain.replace('_', ' ').title()} ({len(domain_df)} signals)")
    md.append("")
    for _, row in domain_df.iterrows():
        md.append(f"### {row['signal_id']}: {row['signal_name']}")
        md.append(f"- **Domain**: {row['domain']}")
        md.append(f"- **Formula**: `{row['formula']}`")
        md.append(f"- **Required Inputs**: {row['required_inputs']}")
        md.append(f"- **Direction**: {row['direction']}")
        md.append(f"- **Priority**: {row['priority']}")
        md.append(f"- **Data Status**: {row['data_status']}")
        md.append("")

with open(BASE / "over_signal_catalog.md", "w") as f:
    f.write("\n".join(md) + "\n")
print(f"Saved: over_signal_catalog.md")

# ── TOP 20 READY + HIGH ─────────────────────────────────────────────
print(f"\n=== TOP 20: HIGH priority + READY data ===")
top20 = df[(df["priority"] == "HIGH") & (df["data_status"] == "READY")]
print(f"Found: {len(top20)} signals")
for _, row in top20.iterrows():
    print(f"  {row['signal_id']}: {row['signal_name']} — {row['formula'][:60]}")

# Also show HIGH + DERIVABLE
print(f"\n=== HIGH priority + DERIVABLE ===")
derivable = df[(df["priority"] == "HIGH") & (df["data_status"] == "DERIVABLE")]
print(f"Found: {len(derivable)} signals")
for _, row in derivable.iterrows():
    print(f"  {row['signal_id']}: {row['signal_name']} — {row['formula'][:60]}")

print("\nDone.")
