# NCAAF opinion views, Sat 2026-09-26 (CFBD week 4, PILOT). Written 12:15-12:45Z from the research
# reports gathered this morning (sources dated Sept 20-26). One entry per game.
# sp = my adjustment to the market's HOME margin, in points (+ = home better than the number,
#      - = away better). tot = my adjustment to the market total, in points (+ over, - under).
# The moneyline takes the same direction as the spread (same idea, same reason).
# Keys are (away fragment, home fragment) matched against the tape's team names.
VIEWS = [
 ("UNLV", "Akron", -0.5, -1.0, "injury_news", "Akron QB Broughton status unclear; Akron 0-13 at home vs FBS non-con", "SP+ 33-18 sits under 52.5; Akron offense thin if Broughton sits"),
 ("Ball State", "Kent State", -0.5, -1.0, "matchup", "Two 1-2 MAC teams; Ball State has won 4 straight in the series, 3 pts is enough", "Both scored 3 or fewer vs FBS power teams; neither offense trusted"),
 ("Colorado", "Baylor", 1.5, -1.0, "injury_news", "Lagway back for Baylor; Colorado lost 41-7 to NW, RB/WR/OL starters out, 6 straight Big 12 road Ls", "Colorado offense scored 14 and 7 vs FBS; injuries at RB and WR"),
 ("Virginia Tech", "Boston College", 1.5, -4.0, "weather", "Nor'easter wind compresses scoring, so the 14-pt dog gains; VT may start 2 backup OL", "Nor'easter: rain all game, 25-35 mph sustained wind, gusts 40+; passing and kicking both suffer"),
 ("Bucknell", "Pittsburgh", -1.5, -2.0, "game_script", "53.5 is huge; Pitt homecoming will empty the bench by the half", "Bucknell scored 14 and 7 in two FCS games; Pitt reserves late; 63 needs Pitt near 60"),
 ("Colorado State", "UTSA", 2.0, -1.5, "injury_news", "CSU starter Hejny doubtful (hamstring), backup Farrar left last game (eye); line moved to UTSA", "CSU down to third-string QB in a dome; their scoring falls off a cliff"),
 ("Illinois", "Ohio State", 0.5, -0.5, "injury_news", "Illinois without two starting guards and three TEs vs OSU front; On3 42-13", "Illinois OL/TE depletion limits its half of the total"),
 ("Wake Forest", "Louisville", -0.5, -1.0, "injury_news", "Louisville has 3 OL out (Merz, Close, Secrest) plus punter; hard to cover 12.5 shorthanded", "Wake QB Lopez questionable (hip) and Louisville OL depleted: both offenses dinged"),
 ("Sam Houston", "Texas Tech", 1.0, 0.5, "matchup", "Tech 3-0, 10 straight home wins, beat Houston; Sam Houston lost to Tulsa; CFN 47-10", "CFN 47-10 lands over 56; Tech can score 45+ alone"),
 ("San Diego State", "Toledo", 1.5, -1.0, "matchup", "SDSU 9am body clock, 0 first-half pts in last 2 games, QB 4 INT; Toledo won 8 straight at home", "SDSU offense stalled in both losses; RB Sutton questionable"),
 ("Texas Longhorns", "Tennessee", 0.5, -2.5, "matchup", "Low-scoring view favors the 5.5-pt home dog slightly", "Tennessee true freshman QB's first SEC start vs Texas D; Manning 17/33 164 last week"),
 ("South Alabama", "Kentucky", 0.5, -1.0, "injury_news", "South Alabama starter Davenport uncertain, backup Hollins likely again", "Backup QB for South Alabama drags its half of the total"),
 ("Lindenwood", "Eastern Michigan", -0.5, -0.5, "matchup", "EMU is 1-3 and laying 25.5; weak FBS teams rarely bury FCS sides", "EMU offense has been poor vs everyone but Sac State"),
 ("UCLA", "Maryland", 0.5, -2.0, "weather", "UCLA on a 10:30am body clock in its first Big Ten road trip", "N wind ~17 mph, gusts to 30, possible rain in College Park; Maryland RB room gutted"),
 ("Northern Illinois", "Georgia State", 0.5, 1.0, "matchup", "NIU 0-3 under an interim coach, new OL every week", "NIU ranks last in FBS on third-down defense; Athlon 35-24"),
 ("Notre Dame", "Purdue", 0.5, 1.0, "injury_news", "ND missing S Talich and three OL; 28 is a lot on the road", "Purdue's offense scored 36 and 38 in its losses; CFN 44-16 = 60"),
 ("Central Arkansas", "Florida State", -1.0, -1.0, "game_script", "46.5 is enormous for a 1-2 FSU; starters out by the third quarter", "FSU pulls starters early; UCA dual-threat QB bleeds clock"),
 ("Hawaii", "Wyoming", -1.0, -0.5, "injury_news", "Wyoming lost its C for the year and two CBs to hand surgery; Hawaii off a bye", "Wyoming scored 10 at CMU; total already fell 46 to 44 but both offenses weak"),
 ("Boise State", "Western Michigan", 1.5, -0.5, "matchup", "WMU lost 13-12 at Michigan and is live at home; CFN only Boise by 3", "CFN 26-23 is right on the number; slight under"),
 ("Robert Morris", "Buffalo", -1.5, -1.0, "matchup", "Buffalo's passing leader has 253 yards all year; it scored 13 at PSU and 20 at FIU", "Buffalo offense can't carry a 28.5 spread or a 46 total"),
 ("William", "Duke", -1.0, -1.0, "game_script", "44.5 vs a 3-0 Duke that only threw for 202 vs Stanford; bench early", "Duke not an explosive passing team; reserves play the second half"),
 ("Ole Miss", "Florida", 2.0, 0.5, "injury_news", "Ole Miss has 3 CBs and 2 S out and RB Lacy doubtful; Florida scored 44+ every game", "Florida's pass game vs a gutted secondary, partly offset by Ole Miss losing Lacy"),
 ("Gardner-Webb", "Marshall", -2.0, 1.0, "matchup", "GWU QB Pennington (ex-Marshall) has three 300-yd games; GWU lost at Liberty by 1", "GWU throws it; Marshall QB leads team in rushing and passing"),
 ("Oklahoma", "Georgia", 2.0, -0.5, "injury_news", "OU without LT Fasusi, WRs Carter and Harris, DT Stone questionable; scored 10 and 14 vs FBS", "OU offense may not reach 14; Georgia carries the total alone"),
 ("Iowa", "Michigan", -2.0, -0.5, "injury_news", "Michigan: 2 OL out, 1 doubtful, starting RT questionable; 5.5 is big in a 38.5 game", "Two elite defenses, Michigan OL banged up, Iowa's new QB1 Hank Brown"),
 ("Utah", "Iowa State", -0.5, -2.5, "weather", "Iowa State missing three DTs; Utah can run on them", "Rain on grass, ~15 mph wind; ISU scored 13 at Iowa, Utah allowed 24 all season"),
 ("UConn", "Miami (OH)", -1.0, 1.0, "matchup", "UConn coach Candle 3-1 vs Miami at Toledo; UConn scored 56 and 48", "UConn offense rolling; iHeart 33-32"),
 ("New Mexico Lobos", "New Mexico State", 1.5, 0.5, "matchup", "UNM rotating two QBs, scored 6 at OU; NMSU off a bye at home in the rivalry", "NMSU has 14 plays of 20+ yds; Hedden 282 pass ypg"),
 ("Stonehill", "Ohio", -2.0, -1.5, "injury_news", "Ohio starter Poulos hurt, true freshman Davis may start; laying 34", "Freshman QB and a run D that gave up 266 to South Alabama; slow game"),
 ("TCU", "UCF", -1.0, -1.0, "injury_news", "UCF starter Barnett out (hamstring), backup Jenkins starts; TCU QB Craig leads Big 12", "UCF backup QB; TCU without its kicker"),
 ("North Carolina Central", "East Carolina", -1.5, -1.0, "injury_news", "ECU QB unsettled and WRs banged up; 36.5 too many", "ECU passing game limited by WR injuries"),
 ("Houston Cougars", "Georgia Southern", 1.0, -0.5, "line_move", "Line moved 19 to 17 toward GaSo; Houston RT and DL questionable", "Model 27-22 and Yahoo 38-13 split; slight under"),
 ("Vanderbilt", "Auburn", -0.5, -0.5, "matchup", "Auburn OL gave up 7 sacks and loses Buster; Vandy's QB change already priced", "Freshman QB's first road start; Auburn OL issues"),
 ("South Florida", "Bowling Green", -1.5, 0.5, "matchup", "BGSU 0-3, lost to FCS Tarleton, scored 7 in both FBS games; USF put up 611 yds", "USF can score 40 alone"),
 ("Nebraska", "Michigan State", -1.0, -0.5, "injury_news", "MSU without starting LB Pretzlaff, a S and two OL; Nebraska's outs are reserves", "SI 24-21 lands under 49; MSU QB threw 2 INT vs ND"),
 ("Wisconsin", "Penn State", -0.5, -1.0, "injury_news", "Penn State missing 4 DEs and WR1 Koby Howard; 10 is a lot", "Gusts near 20 mph; PSU without its top WR"),
 ("Delaware", "Virginia", -2.0, 0.5, "matchup", "Delaware led Vandy at half and lost by 9; SI 38-24 and model 31-20 both under 20", "Picks average ~56; slight over"),
 ("LIU", "Florida International", -2.0, -2.0, "matchup", "FIU scored 9, 33, 10 this year; can't lay 35.5", "FIU offense ~17 ppg vs FBS; LIU splits QBs"),
 ("Incarnate Word", "Texas State", -1.5, 1.0, "matchup", "UIW averages 44.7 ppg; Texas State WRs Sample, Sparks, Evans questionable", "UIW scores, Texas State scored 49 last week; 93F heat"),
 ("James Madison", "Old Dominion", -0.5, -2.0, "weather", "ODU QB 8/20 for 94 last week; JMU D allows 9.7 ppg", "21.7 mph wind in Norfolk; two run-first offenses"),
 ("Central Michigan", "Miami Hurricanes", -1.5, -2.0, "game_script", "CMU runs the ball (26 passes all year) and shortens the game; 41 is huge", "Every CMU game has gone under; CMU scores 14.7 ppg"),
 ("Louisiana", "Charlotte", -1.0, 0.5, "matchup", "Charlotte 0-3, lost to The Citadel, allows ~37 ppg", "Charlotte's defense is the worst unit on the field"),
 ("South Carolina", "Alabama", 1.5, 1.0, "injury_news", "SC loses starting DT Brownlow-Dindy and OT Thompson; Bama gets Dear and Rogers back", "Bama scored 45+ every game; Sellers turnover-prone; CFN 38-26"),
 ("Kennesaw", "Arkansas State", 0.5, -0.5, "line_move", "Line moved 5.5 to 6.5 toward Arkansas State", "Total moved down a point"),
 ("Kansas State", "Cincinnati", 1.0, -0.5, "matchup", "Cincinnati 3-0 at home in the Big 12 opener; 6.5 is generous", "Algorithm 27-25 sits under 55"),
 ("Middle Tennessee", "Jacksonville State", 0.5, 0.5, "matchup", "Dimers 30-22 gives JSU 8 at home", "Dimers 52 total"),
 ("Mercyhurst", "Western Kentucky", -2.0, -2.0, "injury_news", "WKU 0-3, outscored 157-34, QB unsettled, RT and WR1 out; 40.5 too many", "WKU offense scored 34 in 3 games"),
 ("Oklahoma State", "West Virginia", 0.5, 0.5, "injury_news", "OSU without LT Nelson; WVU near full strength at home", "Total rose 58.5 to 61; CFN 34-30"),
 ("Southern Miss", "Tulane", 1.5, -1.5, "injury_news", "Southern Miss starter Hampton out (throwing hand), backup Lyddy, WR Page out", "Backup QB and no WR1 for USM"),
 ("Appalachian", "NC State", -1.0, -0.5, "matchup", "App State 3-0 allowing 16 ppg; 14 is a lot for a 1-2 NC State", "App defense solid; slight under"),
 ("Arizona", "Washington State", 1.0, -0.5, "injury_news", "Arizona WR1 Richardson questionable; insiders call it a trap game", "WSU kicker 1-for-5; predictions cluster 45-53"),
 ("Houston Baptist", "North Texas", -1.0, 0.5, "game_script", "37.5 in 92F heat on UNT Senior Day; reserves play late", "UNT QB threw for 492 last week"),
 ("Texas A&M", "LSU", 0.5, -0.5, "injury_news", "A&M lost WR Bussey for the year and RB Morrow is doubtful; LSU 25-2 in home night games", "A&M skill depletion; Covers leans under"),
 ("Oregon Ducks", "USC", 1.5, -0.5, "injury_news", "Oregon without WR1 McClellan and RB Price, WR Lott doubtful; USC 4-0 at home", "Oregon's pass game thinned; slight under"),
 ("Troy", "Utah State", -2.5, -1.0, "matchup", "USU 0-3 scoring 10.3 ppg, QB a game-time call with 8 INT between them; Troy held Mizzou to 230 yds", "USU offense can't score; total already fell 49 to 47"),
 ("Missouri", "Mississippi State", 1.0, 0.5, "injury_news", "Missouri without RBs Hardy and Fonoti; MSU 3-0 at home", "CFN 34-26 = 60"),
 ("Tulsa", "Arkansas", -1.5, -1.5, "matchup", "Tulsa D allows 9 ppg; Arkansas lost by 33 and 28 and is in crisis; predictions within 3", "Tulsa backup QB Williams starts; both predictions under 50"),
 ("Florida Atlantic", "UL Monroe", -0.5, -0.5, "matchup", "ULM lost to an FCS team, 11 straight losses; FAU QB leads nation in completions", "BR 35-20 = 55"),
 ("Missouri State", "SMU", -1.0, 0.5, "matchup", "Mo State coach was SMU's OC for 4 years; SMU D gave up 265 rush yds", "Predictions 66 and 58"),
 ("Oregon State", "UTEP", -1.0, -0.5, "matchup", "UTEP lost 51-0 and 52-17; Oregon State's Atkinson threw 6 TD last week", "BR 34-19 = 53"),
 ("UMass", "Sacramento State", 1.0, -0.5, "matchup", "UMass's first trip to California, 9pm ET kickoff; home side gets the travel edge", "Split predictions; slight under"),
 ("Rice", "Fresno State", -0.5, -0.5, "injury_news", "Rice without star RB Quinton Jackson but the option shortens games; 13.5 in a 44.5 total", "Option offense and Fresno's slow pace"),
 ("Air Force", "Nevada", -0.5, -0.5, "line_move", "Line moved 4.5 to 5.5 toward Air Force; AF off a bye, 319 rush ypg", "Air Force's option drains the clock"),
 ("Georgia Tech", "Stanford", 0.5, -1.5, "injury_news", "GT without LT, DE and S starters on a cross-country trip", "Stanford scored 6 and 7 vs Miami and Duke"),
 ("Minnesota", "Washington", -0.5, -1.0, "injury_news", "UW without RBs Washington, Limar and Carr; Fleck practiced at night for the late kick", "UW run game depleted; CFN 26-20, Yahoo 27-14"),
]
SIGMA_MARGIN, SIGMA_TOTAL = 15.0, 14.0
